---
- name: 'Check epel repo'
  stat: path=/etc/yum.repos.d/epel.repo
  register: epel_file
  when: ansible_pkg_mgr == 'yum'

- name: 'Add epel repo'
  template: src=epel.repo
        dest=/etc/yum.repos.d/epel.repo
        owner=root group=root mode=0644
  when: ansible_pkg_mgr == 'yum' and not epel_file.stat.exists

- name: 'Installs haproxy as well as socat for socket api'
  yum: name={{ item }} state=latest
  with_items:
    - haproxy
    - socat
  when: ansible_os_family == 'RedHat'

- name: 'Add haproxy apt repo'
  sudo: yes
  apt_repository: repo="ppa:vbernat/haproxy-1.5" state=present update_cache=yes
  when: ansible_os_family == "Debian"

- name: 'Installs haproxy as well as socat for socket api'
  apt: pkg={{ item }} state=latest
  with_items:
    - haproxy
    - socat
  when: ansible_os_family == 'Debian'

- name: 'Installs haproxy as well as socat for socket api'
  pkgin: name={{ item }} state=present
  with_items:
    - haproxy
    - socat
  when: ansible_os_family == 'Solaris'

- name: 'Enable it'
  service: name=haproxy enabled=yes

- name: 'Ensure chroot directory exists'
  file: name={{ haproxy_global.chroot }} state=directory
  when: haproxy_global.chroot is defined and haproxy_global.chroot 
